export interface Product {
  id: number;
  name: string;
  price: number;
  image: string;
  category: string;
  collection: string;
  isNew: boolean;

  grams?: string;
  
  description?: string;
  material?: string;
  weight?: string;
  dimensions?: string;
  inStock?: boolean;
  rating?: number;
  reviews?: number;
}

export const products: Product[] = [
  {
    id: 1,
    name: "Kumkum Box",
    price: 1000,
    image: "/silver-kumkumbox-2.5g-1.webp",
    category: "KumKumBox",
    collection: "daily-wear",
    isNew: false,
  },
  {
    id: 2,
    name: "Kumkum Box",
    price: 1000,
    image: "/silver-kumkumbox-5g-1.webp",
    category: "KumKumBox",
    collection: "daily-wear",
    isNew: false,
  },
  
  {
    id: 3,
    name: "Kumkum Box",
    price: 1000,
    image: "/silver-kumkumbox-8g-1.webp",
    category: "KumKumBox",
    collection: "daily-wear",
    isNew: false,
  },
  
  {
    id: 4,
    name: "Silver Diya",
    price: 1000,
    image: "/silver-diya-5g-1.webp",
    category: "Diya",
    collection: "daily-wear",
    isNew: false,
  },
  {
    id: 5,
    name: "Silver Diya",
    price: 1000,
    image: "/silver-diya-9g-1.webp",
    category: "Diya",
    collection: "daily-wear",
    isNew: false,
  },
  {
    id: 6,
    name: "Silver Plate",
    price: 1200,
    image: "/silver-plate-5g-1.webp",
    category: "Plates",
    collection: "daily-wear",
    isNew: false,
  },
  {
    id: 7,
    name: "Butterfly Toe Ring",
    price: 2520,
    image: "/butterfly-3g-1.webp",
    category: "ToeRings",
    collection: "daily-wear",
    isNew: false,
  },
  {
    id: 8,
    name: "Peacock Toe Ring",
    price: 2520,
    image: "/peacock-3g-1.webp",
    category: "ToeRings",
    collection: "daily-wear",
    isNew: false,
  },
  {
    id: 9,
    name: "Flower Toe Ring",
    price: 2520,
    image: "/flower-3g-1.webp",
    category: "ToeRings",
    collection: "daily-wear",
    isNew: false,
  },
  {
    id: 10,
    name: "Rounded Toe Ring",
    price: 2520,
    image: "/rounded-3g-1.webp",
    category: "ToeRings",
    collection: "daily-wear",
    isNew: false,
  },
  {
    id: 11,
    name: "Silver coins",
    price: 8500,
    image: "/silver-coin-1g.webp",
    category: "Coins",
    collection: "daily-wear",
    isNew: false,
  },
  {
    id: 12,
    name: "Silver coins",
    price: 8500,
    image: "/silver-coin-2g.webp",
    category: "Coins",
    collection: "daily-wear",
    isNew: false,
  },
  {
    id: 13,
    name: "Silver coins",
    price: 8500,
    image: "/silver-coin-5g.webp",
    category: "Coins",
    collection: "daily-wear",
    isNew: false,
  },
  {
    id: 14,
    name: "Silver Glass",
    price: 4200,
    image: "/5g-glass.webp",
    category: "Glass",
    collection: "daily-wear",
    isNew: false,
  },
  {
    id: 15,
    name: "Silver flower",
    price: 4200,
    image: "/silver-flower-5g-1.webp",
    category: "Flower",
    collection: "daily-wear",
    isNew: false,
  },
  {
    id: 16,
    name: "Silver leaf",
    price: 4200,
    image: "/2g-Mango-leaf.webp",
    category: "leaf",
    collection: "daily-wear",
    isNew: false,
  },
  {
    id: 17,
    name: "Silver leaf",
    price: 4200,
    image: "/2g-peepal-leaf.webp",
    category: "leaf",
    collection: "daily-wear",
    isNew: false,
  },
  {
    id: 18,
    name: "Silver srichakra",
    price: 4200,
    image: "/2g-Srichakra.webp",
    category: "srichakra",
    collection: "daily-wear",
    isNew: false,
  },
  {
    id: 19,
    name: "SilverRakhi",
    price: 250,
    image: "/rakhi-1.webp",
    category: "rakhi",
    collection: "daily-wear",
    isNew: true,
  },
  {
    id: 20,
    name: "SilverRakhi",
    price: 250,
    image: "/rakhi-2.webp",
    category: "rakhi",
    collection: "daily-wear",
    isNew: true,
  },
  {
    id: 21,
    name: "SilverRakhi",
    price: 250,
    image: "/rakhi-3.webp",
    category: "rakhi",
    collection: "daily-wear",
    isNew: true,
  },
  {
    id: 22,
    name: "SilverRakhi",
    price: 250,
    image: "/rakhi-4.webp",
    category: "rakhi",
    collection: "daily-wear",
    isNew: true,
  },
  {
    id: 23,
    name: "SilverRakhi",
    price: 250,
    image: "/rakhi-5.webp",
    category: "rakhi",
    collection: "daily-wear",
    isNew: true,
  },
  {
    id: 24,
    name: "SilverRakhi",
    price: 250,
    image: "/rakhi-6.webp",
    category: "rakhi",
    collection: "daily-wear",
    isNew: true,
  },
  {
    id: 25,
    name: "SilverRakhi",
    price: 250,
    image: "/rakhi-7.webp",
    category: "rakhi",
    collection: "daily-wear",
    isNew: true,
  },
  {
    id: 26,
    name: "SilverRakhi",
    price: 250,
    image: "/rakhi-8.webp",
    category: "rakhi",
    collection: "daily-wear",
    isNew: true,
  },
  {
    id: 27,
    name: "SilverRakhi",
    price: 250,
    image: "/rakhi-9.webp",
    category: "rakhi",
    collection: "daily-wear",
    isNew: true,
  },
  {
    id: 28,
    name: "SilverRakhi",
    price: 250,
    image: "/rakhi-10.webp",
    category: "rakhi",
    collection: "daily-wear",
    isNew: true,
  },
  {
    id: 29,
    name: "SilverRakhi",
    price: 250,
    image: "/rakhi-11.webp",
    category: "rakhi",
    collection: "daily-wear",
    isNew: true,
  },
  {
    id: 30,
    name: "SilverRakhi",
    price: 250,
    image: "/rakhi-12.webp",
    category: "rakhi",
    collection: "daily-wear",
    isNew: true,
  },
  {
    id: 31,
    name: "SilverRakhi",
    price: 250,
    image: "/rakhi-13.webp",
    category: "rakhi",
    collection: "daily-wear",
    isNew: true,
  },
  {
    id: 32,
    name: "SilverRakhi",
    price: 250,
    image: "/rakhi-14.webp",
    category: "rakhi",
    collection: "daily-wear",
    isNew: true,
  },
  {
    id: 33,
    name: "SilverRakhi",
    price: 250,
    image: "/rakhi-15.webp",
    category: "rakhi",
    collection: "daily-wear",
    isNew: true,
  },
  {
    id: 34,
    name: "SilverRakhi",
    price: 250,
    image: "/rakhi-16.webp",
    category: "rakhi",
    collection: "daily-wear",
    isNew: true,
  },
  {
    id: 35,
    name: "SilverRakhi",
    price: 250,
    image: "/rakhi-17.webp",
    category: "rakhi",
    collection: "daily-wear",
    isNew: true,
  },
  {
    id: 36,
    name: "SilverRakhi",
    price: 250,
    image: "/rakhi-18.webp",
    category: "rakhi",
    collection: "daily-wear",
    isNew: true,
  },
  {
    id: 37,
    name: "SilverRakhi",
    price: 250,
    image: "/rakhi-19.webp",
    category: "rakhi",
    collection: "daily-wear",
    isNew: true,
  },
  {
    id: 38,
    name: "SilverRakhi",
    price: 250,
    image: "/rakhi-20.webp",
    category: "rakhi",
    collection: "daily-wear",
    isNew: true,
  },
  {
    id: 39,
    name: "SilverRakhi",
    price: 250,
    image: "/rakhi-21.webp",
    category: "rakhi",
    collection: "daily-wear",
    isNew: true,
  },
  {
    id: 40,
    name: "SilverRakhi",
    price: 250,
    image: "/rakhi-22.webp",
    category: "rakhi",
    collection: "daily-wear",
    isNew: true,
  },
  {
    id: 41,
    name: "SilverRakhi",
    price: 250,
    image: "/rakhi-23.webp",
    category: "rakhi",
    collection: "daily-wear",
    isNew: true,
  },
  {
    id: 42,
    name: "SilverRakhi",
    price: 250,
    image: "/rakhi-24.webp",
    category: "rakhi",
    collection: "daily-wear",
    isNew: true,
  },
  {
    id: 43,
    name: "SilverRakhi",
    price: 250,
    image: "/rakhi-25.webp",
    category: "rakhi",
    collection: "daily-wear",
    isNew: true,
  },
  {
    id: 44,
    name: "SilverRakhi",
    price: 250,
    image: "/rakhi-26.webp",
    category: "rakhi",
    collection: "daily-wear",
    isNew: true,
  },
  {
    id: 45,
    name: "SilverRakhi",
    price: 250,
    image: "/rakhi-27.webp",
    category: "rakhi",
    collection: "daily-wear",
    isNew: true,
  },
  {
    id: 46,
    name: "SilverRakhi",
    price: 250,
    image: "/rakhi-28.webp",
    category: "rakhi",
    collection: "daily-wear",
    isNew: true,
  },
  {
    id: 47,
    name: "SilverRakhi",
    price: 250,
    image: "/rakhi-29.webp",
    category: "rakhi",
    collection: "daily-wear",
    isNew: true,
  },
  {
    id: 48,
    name: "SilverRakhi",
    price: 250,
    image: "/rakhi-30.webp",
    category: "rakhi",
    collection: "daily-wear",
    isNew: true,
  },
  {
    id: 49,
    name: "SilverRakhi",
    price: 250,
    image: "/rakhi-31.webp",
    category: "rakhi",
    collection: "daily-wear",
    isNew: true,
  },
  {
    id: 50,
    name: "SilverRakhi",
    price: 250,
    image: "/rakhi-32.webp",
    category: "rakhi",
    collection: "daily-wear",
    isNew: true,
  },
  {
    id: 51,
    name: "SilverRakhi",
    price: 250,
    image: "/rakhi-33.webp",
    category: "rakhi",
    collection: "daily-wear",
    isNew: true,
  },
  {
    id: 52,
    name: "SilverRakhi",
    price: 250,
    image: "/rakhi-34.webp",
    category: "rakhi",
    collection: "daily-wear",
    isNew: true,
  },
  {
    id: 53,
    name: "SilverRakhi",
    price: 250,
    image: "/rakhi-35.webp",
    category: "rakhi",
    collection: "daily-wear",
    isNew: true,
  },
  {
    id: 54,
    name: "SilverRakhi",
    price: 250,
    image: "/rakhi-36.webp",
    category: "rakhi",
    collection: "daily-wear",
    isNew: true,
  },
  {
    id: 55,
    name: "SilverRakhi",
    price: 250,
    image: "/rakhi-37.webp",
    category: "rakhi",
    collection: "daily-wear",
    isNew: true,
  },
  {
    id: 56,
    name: "SilverRakhi",
    price: 250,
    image: "/rakhi-38.webp",
    category: "rakhi",
    collection: "daily-wear",
    isNew: true,
  },
  {
    id: 57,
    name: "SilverRakhi",
    price: 250,
    image: "/rakhi-39.webp",
    category: "rakhi",
    collection: "daily-wear",
    isNew: true,
  },
  {
    id: 58,
    name: "SilverRakhi",
    price: 250,
    image: "/rakhi-40.webp",
    category: "rakhi",
    collection: "daily-wear",
    isNew: true,
  },
  

];

export const categories = [
  "All",
  "KumKumBox",
  "Diya",
  "Plates",
  "ToeRings",
  "Glass",
  "Flower",
  "leaf",
  "srichakra",
];